### ISSUE TITLE
Failed to load extension from: .Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by unipheas** [mp-coder/translate-dev-tools#1]
Trying to install on the Mac is a little different. You'll need to go into the **/Applications** directory then right click on the WeChat MP IDE and choose **"Show Package Contents"**. 

![screen shot 2017-09-16 at 11 04 40](https://user-images.githubusercontent.com/16819233/30508743-810fa6a6-9ad0-11e7-94a0-d69f08d20a20.jpg)

Once I was in there I had to navigate to **Contents/_CodeSignature/Resources/app.nw** to find the same file structure as in the .zip file. 

![screen shot 2017-09-16 at 11 05 23](https://user-images.githubusercontent.com/16819233/30508744-8977f1cc-9ad0-11e7-809f-f849071e2060.jpg)

I then replaced all the files individually, all following the file structure in the .zip file.

![screen shot 2017-09-16 at 11 09 12](https://user-images.githubusercontent.com/16819233/30508747-8ef72e38-9ad0-11e7-80c9-2c4428b55d0d.jpg)

I then started the application and got the following error: **"Failed to load extension from: .Manifest file is missing or unreadable"**

![screen shot 2017-09-16 at 11 09 23](https://user-images.githubusercontent.com/16819233/30508749-988cd380-9ad0-11e7-9a24-c89a57e65001.jpg)

**Comment by willish** [comment]
Would it be possible for you, from a clean install of latest devtools, to zip up the `resources` directory and upload it here? To save space, there is no need for the `static` or `node_modules` subdirectories. 

Then I can compare it to the windows version and find any differences :D

**Comment by willish** [comment]
Another thing, I just noticed the _CodeSignature directory. So perhaps by changing those script files, it is invalidating the signature :(

Another thing (from a clean install) is to try is to make a small change to one of the files and see if it breaks things. e.g. changing the locale from `zh` to `en` in  `js/common/locales/index.js`

**Comment by unipheas** [comment]
I modified the index.js file as you asked and it didn't break.

Here are the files you requested. 

[Resources.zip](https://github.com/mp-coder/translate-dev-tools/files/1308107/Resources.zip)

**Comment by willish** [comment]
The simplest thing is probably to create another release for MAC, as there are some platform specific strings that I had not noticed. Also the filenames seem to be different also in the `nw/js`  directory.

So we can have an `app.nw` zip file for MAC and a `package.nw` for windows, which can just be extracted over.

This could work for the meantime.  Later on I can try to make a real NWJS installer

**Comment by kwnath** [comment]
So what I ended up doing was leaving the package.json as is:

1. Copied over all the .js extension files from the JS folder over to the app.

2. Edit the index.js defaultLocales to  'en'  **app.nw/js/common/locales/index.js**
<img width="465" alt="screen shot 2017-09-18 at 13 39 20" src="https://user-images.githubusercontent.com/26071410/30530136-ca9de290-9c76-11e7-8311-d41ba34d26d0.png">

3. Replace the index.js with the one downloaded in **app.nw/js/common/locales/en/index.js**

I believe the reason why it's messing up is mainly to do with the package.json, the two are structured differently (It was the only combination that didn't work)

**Comment by willish** [comment]
Did you copy over the `.js` files in the root of the `/js/` directory? The ones with hexadecimal names?

Yeah there are some platform-specific strings like paths in the package.json

It would be great if someone can make a zip file for Mac, like there is for windows. So a mac user can just extract it over their installation directory :D

**Comment by kwnath** [comment]
Yes I copied over to the root direction of /js/ 

I'll compress mine and send it over.

**Comment by unipheas** [comment]
The issue has been resolved by @kwnath
